In [51]:
import torch
from torch import tensor
import torchvision
from torchvision import transforms
import PIL


In [52]:
torch.randint(1,7,(2,2),dtype=torch.int32)
#torch.zeros(2,2,dtype=torch.int32)

tensor([[4, 5],
        [6, 5]], dtype=torch.int32)

In [53]:
def to_shape(tensor, *shape):
  return tensor.reshape(*shape)

In [54]:
# Example usage:
flat_tensor = torch.rand(12)
viewed_tensor = flat_tensor.view(3, 2, 2)

# Reshape using to_shape()
reshaped_tensor = to_shape(viewed_tensor, 2, 3, 2)
print(reshaped_tensor)

tensor([[[0.8832, 0.1076],
         [0.6367, 0.4717],
         [0.4357, 0.3110]],

        [[0.2429, 0.0963],
         [0.4531, 0.4013],
         [0.0834, 0.4709]]])


In [55]:
torch.__version__

'2.5.1+cu124'

In [56]:
torch.cuda.is_available()

False

In [57]:
# if torch.cuda.is_available():
#     device = torch.device("cuda")
# else:
#     device = torch.device("cpu")

# print(device)
# print(type(device))
# print(type(viewed_tensor))

if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"
print(type(device))
tensor = torch.randn(3, 3)
tensor=tensor.to(torch.device(device))
print(type(tensor))

<class 'str'>
<class 'torch.Tensor'>


In [60]:
scalar=torch.tensor(7)

In [61]:
print(scalar)

tensor(7)


In [62]:
print(scalar.item())

7


In [64]:
print(scalar.ndim)

0


In [68]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype
zeros = torch.zeros(3,4)
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [70]:
ones = torch.ones(size=(3, 4),dtype=torch.int32)
print(ones)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


In [75]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
zeros_like = torch.zeros_like(input=zero_to_ten)
ones_like = torch.ones_like(input=zero_to_ten)
zeros_like,ones_like

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [77]:
zero_to_ten = torch.arange(start=0.1, end=10.1, step=1)
zero_to_ten

tensor([0.1000, 1.1000, 2.1000, 3.1000, 4.1000, 5.1000, 6.1000, 7.1000, 8.1000,
        9.1000])

In [78]:
zeros_like = torch.zeros_like(input=zero_to_ten)
ones_like = torch.ones_like(input=zero_to_ten)
zeros_like,ones_like

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [83]:
tensor=torch.tensor([1,2,3])
tensor+=10
print(tensor)

tensor([11, 12, 13])


In [81]:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)


tensor([11, 12, 13]) * tensor([11, 12, 13])
Equals: tensor([121, 144, 169])


In [89]:
import torch

torch.manual_seed(42)  # Set seed

# Generate a random tensor
tensor1 = torch.rand(3)
print(tensor1)

# Set the seed again and generate another tensor
torch.manual_seed(42)
tensor2 = torch.rand(3)
print(tensor2)

# Both tensors will be identical
assert torch.equal(tensor1, tensor2)

tensor([0.8823, 0.9150, 0.3829])
tensor([0.8823, 0.9150, 0.3829])


In [96]:
x_stacked_tensor = torch.stack([tensor, tensor, tensor, tensor], dim=1)
x_stacked_tensor


tensor([[11, 11, 11, 11],
        [12, 12, 12, 12],
        [13, 13, 13, 13]])